<?php

trait ShoppingCartFixtureTrait
{
    protected ShoppingCart $cart;

    protected  function setUp(): void
    {
        //parent::setUp(); // TODO: Change the autogenerated stub
        $this->cart =new ShoppingCart();
    }

    protected  function tearDown(): void
    {
        //parent::tearDown(); // TODO: Change the autogenerated stub
        unset($this->cart);
    }

}