<?php

namespace Fixtures;

use ShoppingCart;
use PHPUnit\Framework\TestCase;

class ShoppingCartTest extends TestCase
{
    protected ShoppingCart $cart;
    protected static $db_connection=false;

    protected  function setUp(): void
    {
        //parent::setUp(); // TODO: Change the autogenerated stub
        $this->cart =new ShoppingCart();
    }

    protected  function tearDown(): void
    {
        //parent::tearDown(); // TODO: Change the autogenerated stub
        unset($this->cart);
    }

    public function testCorrectNumbersOfItems()
    {
        $this->cart->addItem('one');
        $expected =1;
        $result = $this->cart->amount;
        $this->assertEquals($expected,$result);
    }

    public  function testCorrectProductName()
    {
        $this->cart->addItem('Apple');
        $this->assertContains('Apple',$this->cart->cartItems);
    }

    public static function setupBeforeClass():void
    {
        if(self::$db_connection) return;
        self::$db_connection= new \PDO('SQLite:database.db');

    }
}
